# Generated by Django 5.2.8 on 2025-12-25 20:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='page',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
