# Generated by Django 5.2.8 on 2025-12-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_page_fecha_actualizacion_page_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
