# Generated by Django 5.2.8 on 2025-12-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_page_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
